apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - name: simple-webapp
        image: jandresv/test
        ports:
        - containerPort: 8080
        env:
          - name: PROVIDER
            value: TestProvider
  selector:
    matchLabels:
      app: simple-webapp

---

apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: simple-webapp