apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
      - name: simple-frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: VITE_API_URL_GREETING_ENDPOINT
            value: "http://localhost:30001/greeting"

---

apiVersion: v1
kind: Service
metadata:
  name: simple-frontend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    app: simple-frontend
