# ConfigMap with SQL initialization script
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS blue_green;

    USE blue_green;

    CREATE TABLE IF NOT EXISTS greetings (
      id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
      greeting VARCHAR(100)
    );

    INSERT INTO greetings (greeting) VALUES ('hello, hi, how are yah?');
    
    CREATE TABLE IF NOT EXISTS farewells (
      id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
      farewell VARCHAR(100)
    );
    
    INSERT INTO farewells (farewell) VALUES ('adios, good bye, see yah?');
---
# https://github.com/MariaDB/mariadb.org-tools/blob/master/anel/k8s/mariadb/mariadb-deployment-pvc.yaml

# Persistent Volume Claim for MariaDB storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M

---
# https://github.com/MariaDB/mariadb.org-tools/blob/master/anel/k8s/mariadb/mariadb-deployment-pvc.yaml

# Service to expose MariaDB internally
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
      protocol: TCP
  selector:
    app: mariadb

---
# https://github.com/MariaDB/mariadb.org-tools/blob/master/anel/k8s/mariadb/mariadb-deployment-pvc.yaml

# Deployment of MariaDB with environment setup and volume configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.4
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: mysql
        - name: MARIADB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mariadb-pv
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: init-script
        configMap:
          name: mariadb-init
          defaultMode: 0777